// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4rXjgVD5mtp7YZ-cG2Wr9o7UaiAdOsjg',
    appId: '1:448308463066:web:10fa448306b3afb3bfece3',
    messagingSenderId: '448308463066',
    projectId: 'travelogue-app-277c2',
    authDomain: 'travelogue-app-277c2.firebaseapp.com',
    storageBucket: 'travelogue-app-277c2.firebasestorage.app',
    measurementId: 'G-RQJSF0XQ57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA2js48mfyCKdXfBB0cf5o-ECwRRLTRho',
    appId: '1:448308463066:android:3787e794a8129b7cbfece3',
    messagingSenderId: '448308463066',
    projectId: 'travelogue-app-277c2',
    storageBucket: 'travelogue-app-277c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgEp-YPIYYx_qPHGY7PvbrzES_L5ML_jo',
    appId: '1:448308463066:ios:ffe512ff14e9e0b5bfece3',
    messagingSenderId: '448308463066',
    projectId: 'travelogue-app-277c2',
    storageBucket: 'travelogue-app-277c2.firebasestorage.app',
    iosBundleId: 'com.example.travelogueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgEp-YPIYYx_qPHGY7PvbrzES_L5ML_jo',
    appId: '1:448308463066:ios:ffe512ff14e9e0b5bfece3',
    messagingSenderId: '448308463066',
    projectId: 'travelogue-app-277c2',
    storageBucket: 'travelogue-app-277c2.firebasestorage.app',
    iosBundleId: 'com.example.travelogueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4rXjgVD5mtp7YZ-cG2Wr9o7UaiAdOsjg',
    appId: '1:448308463066:web:2bf32ddbba3226f4bfece3',
    messagingSenderId: '448308463066',
    projectId: 'travelogue-app-277c2',
    authDomain: 'travelogue-app-277c2.firebaseapp.com',
    storageBucket: 'travelogue-app-277c2.firebasestorage.app',
    measurementId: 'G-PCR2WYNJN4',
  );
}
